dependencies:
  - name: mq-spring-app
    version: 0.0.12
    repository: http://artifactory-artifactory.tools:8082/artifactory/generic-local/ci
  - name: starboard-report
    version: 0.1.0
    repository: http://artifactory-artifactory.tools:8082/artifactory/generic-local/ci
